### ISSUE TITLE
Insensitive to use the skull emoji to depict death

### ISSUE THREAD

**Issue by raghavio** [IndiaSmile/IndiaSmile.github.io#5]
Hello! You guys have put together a brilliant stats display. Congratulations on that.
I noticed the use of 💀 emoticon for the death counter. I feel it's a little insensitive because it is always used in a joke context. It kind of degrades the magnitude of millions of people losing their lives in a global pandemic.
If we have to use an emoji I'm suggesting maybe the sad face or frowning face. ☹️

Just my 2 cents. Goodluck!

**Comment by devmade** [comment]
The emoji has been updated.
