### ISSUE TITLE
Which api consumed to get nearby lat-long of positive cases per city?

### ISSUE THREAD

**Issue by ms-tii** [IndiaSmile/IndiaSmile.github.io#6]
I am unable to find the api in project which returns cases of particular city or geo location base data. To measure nearby case.

**Comment by namanyayg** [comment]
That data is not available for privacy reasons of the infected. Calculations are approximated using whatever data is received, usually to district level.

**Comment by ms-tii** [comment]
I don't want to show or use data, I am just practicing to make iOS app same like yours which to show nearest confirmed cases. that is why I want to use that api which returns confirmed cases with lat-longs
